import java.util.Random;
import java.util.Scanner;

public class Project1 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();
        System.out.println("Welcome to the game ");
        int computer_number = random.nextInt(100)+1;
        int count = 0;
        while (true){
            System.out.println("Enter your choice : ");
            int user_number = scanner.nextInt();
            count ++;
            if(user_number == computer_number){
                System.out.println("Congratulation ! you have guess the number which is generated by computer.");
                System.out.println("You have guess the number in your " + count + " th attempt");
                break;
            }
            if(user_number < computer_number){
                System.out.println("You are choosing low number.");
            }
            else{
                System.out.println("You are choosing high number.");
            }
        }
    }
}
